### ISSUE TITLE
Zig 0.16 support

### ISSUE THREAD

**Issue by kalapalo** [lalinsky/dusty#15]
trying to run the example and getting this:
```zig
/home/user/.cache/zig/p/zio-0.4.0-xHbVVOdXHACcHf2a5VidyvK70IH0FdWNugm6OyniqBku/vendor/libxev/build.zig:339:16: error: member function expected 1 argument(s), found 0
            cmd.captureStdOut(),
            ~~~^~~~~~~~~~~~~~
/opt/zig/lib/std/Build/Step/Run.zig:652:5: note: function declared here
pub fn captureStdOut(run: *Run, options: CapturedStdIo.Options) std.Build.LazyPath {
~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
referenced by:
    build: /home/user/.cache/zig/p/zio-0.4.0-xHbVVOdXHACcHf2a5VidyvK70IH0FdWNugm6OyniqBku/vendor/libxev/build.zig:119:29
    runBuild__anon_98947: /opt/zig/lib/std/Build.zig:2235:44
    10 reference(s) hidden; use '-freference-trace=12' to see all references
```

I am on linux (manjaro) using zig master.
Is the problem due to zig master ? Should it work with zig 0.15.2 ?
Thanks for your nice & hard working.
